# Generated by Django 5.1 on 2025-09-04 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default=' ')),
                ('discount_percentage', models.IntegerField(default=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('not_started', 'Not_started'), ('active', 'Active'), ('expired', 'Expired')], default='active', max_length=255)),
                ('usage_limit', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyPromotions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('promotions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promotions.promotions')),
            ],
        ),
    ]
