# Generated by Django 5.1 on 2025-09-04 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0008_alter_drivers_profile_picture'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPhoneNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_numbers', to='drivers.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsClients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('phone_number', models.CharField(max_length=255)),
                ('payments_method', models.CharField(choices=[('orange_money', 'Orange_money'), ('mtn_money', 'Mtn_money'), ('credit_card', 'credit_card')], default='orange_money', max_length=255)),
                ('payments_status', models.CharField(choices=[('in_pending', 'In_pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('rides_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rides.rides')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsDrivers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('payments_method', models.CharField(choices=[('orange_money', 'Orange_money'), ('mtn_money', 'Mtn_money'), ('credit_card', 'credit_card')], default='orange_money', max_length=255)),
                ('payments_status', models.CharField(choices=[('in_pending', 'In_pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='in_pending', max_length=255)),
                ('payments_type', models.CharField(choices=[('wallet_pay', 'wallet_pay'), ('referral_earning', 'referral_earning'), ('driver_subscription', 'driver_subscription'), ('ride_payment', 'ride_payment')], default='wallet_pay', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
    ]
