# Generated by Django 5.1 on 2026-01-19 11:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Wallet Deposit'), ('ride_earning', 'Ride Earning'), ('referral_bonus', 'Referral Bonus'), ('admin_credit', 'Admin Credit'), ('commission_deduction', 'Commission Deduction'), ('subscription_fee', 'Subscription Fee'), ('penalty', 'Penalty'), ('admin_debit', 'Admin Debit')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Commission rate at time of transaction', max_digits=5, null=True)),
                ('grade_name', models.CharField(blank=True, help_text='Driver grade at time of transaction', max_length=50, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='drivers.drivers')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentsdrivers')),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='rides.rides')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', '-created_at'], name='payments_wa_driver__1768bc_idx'), models.Index(fields=['transaction_type', 'status'], name='payments_wa_transac_139ee3_idx')],
            },
        ),
    ]
