# Generated by Django 5.1 on 2025-09-04 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0007_alter_drivers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralsClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('referral_bonus', models.IntegerField(default=50)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_referred', to='clients.clients')),
                ('referrer_client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_referrer', to='clients.clients')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralsDrivers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('referral_bonus', models.IntegerField(default=20)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_driver_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_referred', to='drivers.drivers')),
                ('referrer_driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_referrer', to='drivers.drivers')),
            ],
        ),
    ]
