# Generated by Django 5.1 on 2026-05-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralsclient',
            name='bonus_paid_to_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsclient',
            name='bonus_paid_to_referrer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsclient',
            name='first_ride_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsclient',
            name='referral_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='referralsdrivers',
            name='bonus_paid_to_referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsdrivers',
            name='bonus_paid_to_referrer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsdrivers',
            name='first_ride_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralsdrivers',
            name='referral_bonus_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
