# Generated by Django 5.1 on 2025-07-25 15:45

import django.db.models.deletion
import drivers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('adresse', models.CharField(max_length=255, null=True)),
                ('referral_code', models.CharField(default=None, max_length=20, null=True, unique=True)),
                ('wallet_money', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.baseuser',),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('vehicle_model', models.CharField(default='Not specified', max_length=100)),
                ('license_plate', models.CharField(default='Not specified', max_length=20, unique=True)),
                ('technical_inspection_date', models.DateField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, upload_to=drivers.models.vehicule_directory_path)),
                ('vehicle_rental_contract', models.ImageField(blank=True, upload_to=drivers.models.vehicule_directory_path)),
                ('driving_licence_front', models.ImageField(blank=True, upload_to=drivers.models.vehicule_directory_path)),
                ('driving_licence_back', models.ImageField(blank=True, upload_to=drivers.models.vehicule_directory_path)),
                ('insurrance_file', models.ImageField(blank=True, upload_to=drivers.models.vehicule_directory_path)),
                ('validation_status', models.CharField(choices=[('in pending', 'In pending'), ('rejected', 'Rejected'), ('validated', 'Validated')], default='in pending', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('driver_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
    ]
