# Generated by Django 5.1 on 2025-09-04 06:41

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_alter_drivers_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path),
        ),
    ]
