# Generated by Django 5.1 on 2026-01-05 20:07

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_alter_drivers_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivers',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's phone number has been verified via OTP"),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path),
        ),
    ]
