# Generated by Django 5.1 on 2025-11-04 17:19

import django.db.models.deletion
import drivers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_drivers_is_phone_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du grade (ex: Standard, Bronze, Silver, Gold, Platinum)', max_length=50, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Taux de commission en pourcentage (ex: 20.00 pour 20%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce grade est actuellement utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'ordering': ['commission_rate'],
            },
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path),
        ),
        migrations.CreateModel(
            name='DriverGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure d'attribution du grade")),
                ('unassigned_at', models.DateTimeField(blank=True, help_text='Date et heure de fin de validité du grade (si le grade a été retiré)', null=True)),
                ('is_current', models.BooleanField(default=True, help_text="Indique si c'est le grade actuel du chauffeur")),
                ('reason', models.TextField(blank=True, help_text="Raison de l'attribution ou du retrait du grade (optionnel)", null=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant attribué le grade (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(help_text='Chauffeur associé à ce grade', on_delete=django.db.models.deletion.CASCADE, related_name='grade_history', to='drivers.drivers')),
                ('grade', models.ForeignKey(help_text='Grade attribué au chauffeur', on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='drivers.grade')),
            ],
            options={
                'verbose_name': 'Grade du chauffeur',
                'verbose_name_plural': 'Grades des chauffeurs',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='drivers',
            name='grades',
            field=models.ManyToManyField(help_text='Grades associés à ce chauffeur (historique et actuel)', related_name='drivers', through='drivers.DriverGrade', to='drivers.grade'),
        ),
        migrations.CreateModel(
            name='GradeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('rating', 'Note moyenne minimale'), ('rides_count', 'Nombre minimum de courses'), ('revenue', "Chiffre d'affaires minimum"), ('referrals', 'Nombre minimum de parrainages')], help_text="Type d'exigence (note, nombre de courses, etc.)", max_length=20)),
                ('comparison_operator', models.CharField(choices=[('>=', 'Supérieur ou égal à'), ('>', 'Supérieur à'), ('==', 'Égal à')], default='>=', help_text="Opérateur de comparaison pour évaluer l'exigence", max_length=2)),
                ('value', models.DecimalField(decimal_places=2, help_text="Valeur seuil à atteindre pour satisfaire l'exigence", max_digits=10)),
                ('description', models.TextField(blank=True, help_text="Description conviviale de l'exigence (optionnel)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(help_text='Grade associé à cette exigence', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='drivers.grade')),
            ],
            options={
                'verbose_name': 'Exigence de grade',
                'verbose_name_plural': 'Exigences de grade',
                'ordering': ['grade__commission_rate', 'requirement_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='drivergrade',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('driver',), name='unique_current_grade_per_driver'),
        ),
        migrations.AlterUniqueTogether(
            name='graderequirement',
            unique_together={('grade', 'requirement_type')},
        ),
    ]
