# Generated by Django 5.1 on 2025-11-05 06:23

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_grade_alter_drivers_profile_picture_drivergrade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivergrade',
            name='assigned_by',
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path),
        ),
    ]
