# Generated by Django 5.1 on 2026-01-19 11:52

import drivers.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0011_remove_drivergrade_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='prestation',
            field=models.CharField(choices=[('economy', 'Economy'), ('confort', 'Confort'), ('prestige', 'Prestige')], default='economy', help_text='Type of service this vehicle provides', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='wallet_money',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Driver wallet balance in FCFA', max_digits=12),
        ),
    ]
