# Generated by Django 5.1 on 2026-01-19 12:14

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0012_vehicle_prestation_alter_drivers_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='criminal_record_certificate',
            field=models.FileField(blank=True, help_text='Criminal record certificate (required for prestige vehicles) - Accepts PDF, images, and other document formats', null=True, upload_to=drivers.models.vehicule_directory_path),
        )
    ]
