# Generated by Django 5.1 on 2026-01-28 07:25

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0013_vehicle_criminal_record_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='technical_control_document',
            field=models.FileField(blank=True, help_text='Technical control document (required for prestige vehicles) - Accepts PDF, images, and other document formats', null=True, upload_to=drivers.models.vehicule_directory_path),
        )
    ]
