# Generated by Django 5.1 on 2026-04-04 02:59

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0014_vehicle_technical_control_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='criminal_record_expiry_date',
            field=models.DateField(blank=True, help_text="Date d'expiration du casier judiciaire (généralement 3 mois)", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='criminal_record_validated_at',
            field=models.DateTimeField(blank=True, help_text="Date de validation du casier judiciaire par l'admin", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driving_licence_expiry_date',
            field=models.DateField(blank=True, help_text="Date d'expiration du permis de conduire", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driving_licence_validated_at',
            field=models.DateTimeField(blank=True, help_text="Date de validation du permis par l'admin", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text="Date d'expiration de l'assurance", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_validated_at',
            field=models.DateTimeField(blank=True, help_text="Date de validation de l'assurance par l'admin", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='technical_control_expiry_date',
            field=models.DateField(blank=True, help_text="Date d'expiration de la visite technique", null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='technical_control_validated_at',
            field=models.DateTimeField(blank=True, help_text="Date de validation de la visite technique par l'admin", null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=drivers.models.vehicule_directory_path),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(default='Not specified', help_text='Modèle du véhicule (ex: Corolla, Civic, C-Class)', max_length=50),
        ),
    ]
