# Generated by Django 5.1 on 2026-09-24 22:46

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0015_vehicle_criminal_record_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(
                default='Not specified',
                help_text='Marque du véhicule (ex: Toyota, Honda, Mercedes)',
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_color',
            field=models.CharField(
                choices=[
                    ('white', 'Blanc'),
                    ('black', 'Noir'),
                    ('gray', 'Gris'),
                    ('silver', 'Argent'),
                    ('blue', 'Bleu'),
                    ('red', 'Rouge'),
                    ('green', 'Vert'),
                    ('yellow', 'Jaune'),
                    ('brown', 'Marron'),
                    ('orange', 'Orange'),
                    ('purple', 'Violet'),
                    ('other', 'Autre'),
                ],
                default='purple',
                help_text='Couleur principale du véhicule',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=drivers.models.vehicule_directory_path,
            ),
        ),
    ]
