# Generated by Django 5.1 on 2026-09-24 22:50

import drivers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0016_vehicle_vehicle_brand_vehicle_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='profile_picture',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=drivers.models.driver_directory_path,
            ),
        ),
    ]
