# Generated by Django 5.1 on 2026-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='is_phone_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's phone number has been verified via OTP"),
        ),
    ]
