# Generated by Django 5.1 on 2025-09-18 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='ride_id',
            field=models.ForeignKey(blank=True, help_text='The associated ride for this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='rides.rides'),
        ),
    ]
