# Generated by Django 5.1 on 2025-11-04 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_fix_ride_field_naming'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF EXISTS (
                                SELECT 1
                                FROM information_schema.columns
                                WHERE table_name = 'support_supportticket'
                                  AND column_name = 'ride_id_id'
                            ) THEN
                                UPDATE support_supportticket
                                SET ride_id = ride_id_id
                                WHERE ride_id IS NULL AND ride_id_id IS NOT NULL;

                                ALTER TABLE support_supportticket
                                DROP COLUMN ride_id_id CASCADE;
                            END IF;
                        END $$;
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RenameField(
                    model_name='supportticket',
                    old_name='ride_id',
                    new_name='ride',
                ),
            ],
        ),
    ]
