# Generated by Django 5.1 on 2025-09-04 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0006_alter_drivers_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('lon_start_location', models.FloatField(default=0.0)),
                ('lon_end_location', models.FloatField(default=0.0)),
                ('lat_start_location', models.FloatField(default=0.0)),
                ('lat_end_location', models.FloatField(default=0.0)),
                ('accepted_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('distance', models.FloatField(default=0.0)),
                ('final_price', models.FloatField(default=0.0)),
                ('prestation', models.CharField(choices=[('economy', 'Economy'), ('confort', 'confort'), ('prestige', 'Prestige')], default='economy', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('accepted_by_driver', 'Accepted by Driver')], default='pending', max_length=255)),
                ('notified_500m', models.BooleanField(default=False)),
                ('notified_arrived', models.BooleanField(default=False)),
                ('mode_of_payments', models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('cash', 'Paiement en espèces')], default='cash', max_length=255)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clients')),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.drivers')),
                ('rides_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rides.rides')),
            ],
        ),
    ]
