name: gateway

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - toya-prod-static:/srv/toya-prod/static:ro
      - toya-prod-media:/srv/toya-prod/media:ro
      - toya-staging-static:/srv/toya-staging/static:ro
      - toya-staging-media:/srv/toya-staging/media:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - gateway

volumes:
  caddy-data:
  caddy-config:
  toya-prod-static:
    external: true
    name: toya-prod_static-data
  toya-prod-media:
    external: true
    name: toya-prod_media-data
  toya-staging-static:
    external: true
    name: toya-staging_static-data
  toya-staging-media:
    external: true
    name: toya-staging_media-data

networks:
  gateway:
    external: true
