# Generated by Django 5.1 on 2025-09-04 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.URLField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('notification_type', models.CharField(choices=[('payment_success', 'Payment_success'), ('payment_failed', 'Payment_failed'), ('ride_canceled', 'Ride_canceled'), ('new_ride', 'NewRide'), ('ride_started', 'Ride_started'), ('ride_accepted', 'Ride_accepted'), ('ride_completed', 'Ride_completed'), ('withdraw_wallet', 'Withdraw_wallet'), ('recharge_wallet', 'Recharge_wallet'), ('course_available', 'Course_available'), ('support_ticket', 'Support_ticket'), ('referral', 'referral'), ('referral_earning', 'referral_earning'), ('vehicle_submission_for_verification', 'vehicle_submission_for_verification'), ('subscription_payment', 'subscription_payment'), ('message_received', 'message_received'), ('support_message_received', 'support_message_received'), ('documents_rejected', 'documents_rejected'), ('documents_approved', 'documents_approved')], max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_to', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
